### PR TITLE
Fix build for >1.9

### PR DESCRIPTION
**Pull request by oscar-izval**
TODO:
- wait for 1.22.4 to be in nixpkgs-unstable, then update flake.lock and try again

### CODE REVIEW

**Comment by sestrella** [comment]
@oscar-izval I tried updating the "nixpkgs-unstable" input in the "flake.lock" file now that Terraform 1.9.2 is available on "nixpkgs". While this resolves the build issue, it consumes a significant amount of time and CI resources; I believe a workaround would be to introduce a new version of "nixpkgs-unstable" for 1.9. What are your thoughts?

**Comment by oscar-izval** [comment]
> @oscar-izval I tried updating the "nixpkgs-unstable" input in the "flake.lock" file now that Terraform 1.9.2 is available on "nixpkgs". While this resolves the build issue, it consumes a significant amount of time and CI resources; I believe a workaround would be to introduce a new version of "nixpkgs-unstable" for 1.9. What are your thoughts?

Yeah... not ideal, but not sure how sustainable the idea of adding new instances of `nixpkgs` is. The way I understand this, we'd need to add a new instance every time Terraform needs a newer version of Go, which is the reason we had to update the nixpkgs-unstable input here. In that case, I'd create a separate instance for each minor version of Go to "bundle" some versions together. While we are at it, I don't remember why we use nixpkgs for <=1.6, could we use unstable for everything?

On the other hand, CI time and resources are essentially free at this point, except for some babysitting if the build fails by being too big (I think that's why it failed last night). Maybe the most cost-effective solution here is to bite the bullet and rebuild everything.

**Comment by sestrella** [comment]
@oscar-izval regarding:

> In that case, I'd create a separate instance for each minor version of Go to "bundle" some versions together

Could you elaborate on this? Do you mean having a separate "nixpkgs" instance for each Go minor version needed to build Terraform?

> While we are at it, I don't remember why we use nixpkgs for <=1.6, could we use unstable for everything?

It is primarily due to a license change on Terraform, which is declared as part of the derivation metadata.

https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/applications/networking/cluster/terraform/default.nix#L56

**Comment by oscar-izval** [comment]
> Could you elaborate on this? Do you mean having a separate "nixpkgs" instance for each Go minor version needed to build Terraform?

Yes, but now that I'm thinking about it again, we'll need to go in and add a new instance every time it's needed, which is not that different from babysitting the build and retriggering it a few times whenever we need a full recompile. From what I can see in the error logs, the issue is
```
> compile: writing output: write $WORK/b1210/_pkg_.a: no space left on device
```
We may want to look into it from that angle too. [Link](https://github.com/actions/runner-images/issues/2875)

**Comment by sestrella** [comment]
> Yes, but now that I'm thinking about it again, we'll need to go in and add a new instance every time it's needed, which is not that different from babysitting the build and retriggering it a few times whenever we need a full recompile.

I guess the main difference is that when we need to upgrade the Go version, it only affects new Terraform versions, while the previous ones remain unchanged and can be pulled from the binary cache. But let us talk more about this internally.

**Comment by sestrella** [comment]
@oscar-izval While you started this PR, I believe I made some changes on top; in that sense, I would avoid the Obama medal approach here and instead open a PR where you could leave comments and give it your final approval. What are your thoughts?

**Comment by oscar-izval** [comment]
Absolutely @sestrella, this work is all yours at this point. I'll make sure to take a look at your new PR :)

**Comment by sestrella** [comment]
It is not about ownership; rather, it is about following up on the proper review process, in which someone else takes a closer look at the proposed changes. Thank you! I would then create a new PR.

**Pull request closed without merging**
